### ISSUE TITLE
help1

### ISSUE THREAD

**Issue by AndrewTechVt** [hadenpf/scam-buddy#1]
google takes me to bing now what idid you my to computer !11!!

**Comment by IWantToScamBait** [comment]
You obviously didn't read the README.md.
The extension redirects you to the 5th page of Bing to fool with scammers. If you want it to stop, here is how.
1. type "about:extensions" into your browser bar.
2. Click "Details" under the extension.
3. Scroll down and disable "Automatically allow access on the following sites"
4. Turn off "*://*.google.com/*" and turn on "*://www.target.com/*"
That's it. Simple.
-Morg
